### ISSUE TITLE
Helm chart maintenance

### ISSUE THREAD

**Issue by bclermont** [goharbor/community#132]
Not sure where to raise that issue... so I'm trying here.

https://github.com/goharbor/harbor-helm/pulls

There is 35 pull requests pending reviews, many of them seem very legits and actually improve and fix this chart.

The chart is still active, I see commits every few days. But the community PR are ignored.  Not even reviewed and changes/rebased asked before merging them.

Is there a community? or the whole point of the maintainers of the helm charts is to solve their own needs and ignore the rest of the world?

**Comment by xaleeks** [comment]
Thanks for the feedback.  The maintainers are currently a little backed up with the upcoming 2.0 release slated for end of April.  If you look at the harbor repo, we are actively engaged with the community and respond pretty fast to issues and PR.  As this is a open source project, it's difficult to commit to specific deadlines for merging these PRs and priorities are quickly shifting.  We'll definitely take a look at some of these helm PRs as we near the release.

**Comment by bclermont** [comment]
> Thanks for the feedback. The maintainers are currently a little backed up with the upcoming 2.0 release slated for end of April.

2.1 is out, I waited 6 months for feedback on this pull request

the situation had not improved, this is not a community project. what is the point to contribute if it's ignore?

You just clearly shown that you don't care about contributors.

I'm also a golang coder, I could help on the non-helm side. but why?
 
I will maintains my improvements on my side, and be a passive user.
