### ISSUE TITLE
community meeting calendar links broken

### ISSUE THREAD

**Issue by christian-korneck** [goharbor/community#153]
hi there, I noticed that the calendar link on [MEETING_SCHEDULE.md](https://github.com/goharbor/community/blob/master/MEETING_SCHEDULE.md) in this repo seems to be broken.

When trying to open it Google Calendar shows the error:
```
This email address isn't associated with an active Google Calendar account: NjdjNWRlMXNxdDRkNXQzNzlvaTByMXJ1YzRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ. Please check the email address and try again.
```

Also the `invite.ics` that new subscribers to the `harbor-users` mailing list are being sent seems to have had its last recurring event:

![image](https://user-images.githubusercontent.com/6320032/107457326-265c3700-6b52-11eb-8e9e-6585d87cbd52.png)

This makes it hard for new users to find out the date of the next community meeting. I'm not sure who owns these accounts, hope this is the right place to post this (apologies if not).

**Comment by doublest** [comment]
yes, please fix this.

**Comment by jonasrosland** [comment]
Hi folks, the Google Calendar will be removed by PR https://github.com/goharbor/community/pull/161, just waiting for approval.

I hope the date for the new invites are correct now? If not, please let me know.

**Comment by yanji09** [comment]
I believe this was fixed now. Hence close it.
