### ISSUE TITLE
maintainers: Promote Tianon Gravi maintainer

### ISSUE THREAD

**Issue by OrlinVasilev** [goharbor/community#176]
This issue holds the voting process to promote him to a maintainer.

Current maintainers, please indicate your approval of this with a comment on this issue.

**Comment by xaleeks** [comment]
LGTM

**Comment by xaleeks** [comment]
@kofj  @danielpacak  @renmaosheng  @steven-zou  @reasonerjt  @jwangyangls  please get your votes in

**Comment by steven-zou** [comment]
@OrlinVasilev 

Can we follow the original way to nominate a new maintainer? Here are some examples: https://github.com/goharbor/community/pulls?q=is%3Apr+is%3Aclosed+nomination+label%3Aarea%2Fmaintainer-nomination

**Comment by OrlinVasilev** [comment]
@steven-zou - was not aware of that so will open PR of course and will update the documentation!

**Comment by OrlinVasilev** [comment]
@steven-zou - https://github.com/goharbor/community/pull/177 here it goes

**Comment by OrlinVasilev** [comment]
Done! Welcome once again @tianon !!!
