### ISSUE TITLE
Harbor and Peritus Slack Assistant

### ISSUE THREAD

**Issue by smsperitus** [goharbor/community#179]
/kind proposal

Thanks for the opportunity to present and demonstrate Peritus.AI to the [Harbor Community on Wednesday, October 20, 2021](https://github.com/goharbor/community/wiki/Harbor-Community-Meetings). Pursuant to the recommendation at the meeting, I am opening this GitHub Issue to request the inclusion of the Peritus Slack Applications in the Harbor Channels on the CNCF Slack Workspace. Since these applications are already installed on the CNCF Slack Workspace, the Harbor channel admins need to enable the Applications (instructions are attached).

[Peritus.AI](https://peritus.ai/) is an ML platform for community-led growth. We are focused on cloud-native technologies to provide community intelligence for developer success. Peritus provides an ML assistant that provides recommendations for questions from Slack users. Peritus is currently offering our platform for free for all non-profit OSS projects.

On-boarding time is typically less than 2 weeks. The sources of the recommendations are Product documentation, Blogs, Slack Channels, StackOverflow, Community Forums, GitHub Issues, etc.

A [short video](https://vimeo.com/592411938/530a5b941c) that demonstrates the Peritus Assistant for Slack.

Ask for the Harbor community:

1. Validate the Harbor published content source list with Peritus 
- Product Documentation: https://goharbor.io/docs/
- Blog: https://goharbor.io/blog/
- GitHub: https://github.com/goharbor
- StackOverflow Tags: harbor (https://stackoverflow.com/questions/tagged/harbor?tab=Newest) 
- Community Forum URL: No community hosted Q&A platform (e.g.: https://discuss.kubernetes.io/)
2. Enable the Peritus Connector on selected active Slack channels for sourcing Slack conversations
- Installation of the Peritus Connector
   - Reason: Sourcing Harbor community channel content
   - URL for installation: https://slack.com/apps/A027CU2L7P0-peritus-connector
   - Requirements: Admin/owner rights for the Slack workspace
3. Enable and promote the Peritus Assistant to community users
- Installation of the Peritus Assistant for Slack 
   - Reason: Enablement of Peritus Assistant for Slack
   - URL for installation: https://slack.com/apps/A0245BNBC0G-peritus-assistant
   - Requirements: Admin/owner rights for the Slack workspace
4. Provide feedback on product experience

[Peritus Assistant and Connector for Slack - Installation Guide.pdf](https://github.com/goharbor/community/files/7464149/Peritus.Assistant.and.Connector.for.Slack.-.Installation.Guide.pdf)

As the Assistant learns, its answers improve. Peritus will actively monitor the performance, and provide periodic updates to the Community. If the Community decides to disconnect the Assistant, Peritus will use their best effort to disconnect the Assistant and all related processes in a reasonable time period and there will be no impact on the Community's slack. The disconnect process can be initiated, approved, and tracked via another Harbor GitHub issue.

**Comment by OrlinVasilev** [comment]
Thank you @smsperitus!!

Here is the video from the last Community Meeting : https://youtu.be/IBxc0ad3KYg and at 19:12 you can see the DEMO!

Please Vote!

**Comment by OrlinVasilev** [comment]
@goharbor/all-maintainers

**Comment by Vad1mo** [comment]
I support the proposal, as it does not add more workload on the maintainers and on that other hand can help new users answer common asked questions.

**Comment by tianon** [comment]
Agreed, seems sane for us to give it a try! +1

**Comment by OrlinVasilev** [comment]
Hi @smsperitus, we discussed and we want to go for it! What are the next steps we should take?

**Comment by OrlinVasilev** [comment]
@smsperitus I think we can close this one as we already have it in both channels?

**Comment by smsperitus** [comment]
Yes, it's good to close. Thanks for the reminder @OrlinVasilev
