### ISSUE TITLE
move to cncf-hosted mailing lists

### ISSUE THREAD

**Issue by clouderati** [goharbor/community#23]
Dan Kohn reached out and recommended that we move our email discussion to CNCF-managed mailing lists:

```
I would recommend moving your dev and user mailing lists from Google Groups to lists.cncf.io to make the web interface accessible inside the Great Firewall.

If you're interested in doing so, Ihor would be happy to arrange the migration for you.
```

I propose we create the following mailing lists:

* **harbor** - general community mailing list
* **harbor-announcements** - notification of new Harbor releases and major news (low-traffic)
* **harbor-dev** - development discussion
* **harbor-maintianers** - for the occasional internal discussion amongst maintainers

If there are no objections by 30nov2018, I will begin working with Ihor and Dan to create the mailing lists and decommission the old Google-group-based lists.

**Comment by clouderati** [comment]
Will also need @cd1989 and @nlowe's email addresses. Please ping me on Slack: `@james`.

**Comment by nlowe** [comment]
Email sent via slack

**Comment by clouderati** [comment]
Hi @idvoretskyi – can you drop me an email so that we can start working on creating the mailing lists above? Many thanks in advance for your help.

**Comment by cd1989** [comment]
Email sent via slack. Sorry for the late response.

**Comment by steven-zou** [comment]
@clouderati 

Are these mail lists ready now? When can we use them?

**Comment by idvoretskyi** [comment]
@steven-zou @clouderati not yet - the plan is to finish migration by the end of the week. Apologies for the delay caused by the holidays.

**Comment by idvoretskyi** [comment]
Synced with @clouderati - migration process has started.

**Comment by clouderati** [comment]
Update: @idvoretskyi pinged me earlier today; looks like the migration will be complete by EoW.

**Comment by idvoretskyi** [comment]
This is done, the following groups are migrated:
harbor-dev@lists.cncf.io 
harbor-users@lists.cncf.io

**Comment by jonasrosland** [comment]
Thanks @idvoretskyi! We'll get the site updated as soon as the new Netlify integration has been completed,

**Comment by idvoretskyi** [comment]
Updated here as well - https://github.com/goharbor/harbor/pull/7092

Thanks, @jonasrosland!

**Comment by steven-zou** [comment]
Work is completed. Close it
