### ISSUE TITLE
clean up labels

### ISSUE THREAD

**Issue by ghost** [goharbor/community#24]
I'd like to clean up labels used in `gohabror/harbor`. We currently have lots of old-ish labels, some that are related to VMware-specific products and projects. Many of these labels are not being used and / or are roughly duplicates of other labels.

## Remove
I propose we **remove** the following labels:
- [ ] 0.5.0-defer
- [ ] 1.1.0-defer
- [ ] 1.2.0-defer
- [ ] 1.4.0-defer
- [ ] 1.5.0-defer
- [ ] 1.6.0-defer
- [ ] area/tile
- [ ] candidate/1.5.1
- [ ] candidate/1.5.2
- [ ] candidate/1.6.0
- [ ] candidate/1.7.0
- [ ] candidate/1.8.0
- [ ] cla-not-required
- [ ] cla-rejected
- [ ] COBD
- [ ] DB change
- [ ] found-in/pks-0.8
- [ ] found-in/pks-1.0
- [ ] kind/advanced
- [ ] kind/impact-ova
- [ ] kind/ux-fit-and-finish (use area/ui or area/ux instead)
- [ ] make
- [ ] message
- [ ] needs/validation
- [ ] new-ui
- [ ] product/pks
- [ ] product/standalone
- [ ] product/vic
- [ ] RFC
- [ ] target/pks-0.8
- [ ] target/pks-1.0
- [ ] target/pks-1.1-stretch
- [ ] target/pks-1.2
- [ ] target/post-1.2.0
- [ ] target/post-1.3.0
- [ ] target/post-1.5.0
- [ ] target/vic-1.3
- [ ] target/1.2.0-stretch
- [ ] target/1.2.0
- [ ] target/1.5.0
- [ ] target/1.5.1
- [ ] target/1.5.4
- [ ] target/1.6.0
- [ ] target/1.6.1
- [ ] target/1.7.0
- [ ] target/1.8.0
- [ ] UX (use area/ux instead)
- [ ] waiting-for-verify (use needs/repro instead)
- [ ] with-admiral

## Rename
I propose we **rename** the following labels:
- [ ] area/devops-support -> area/ops
- [ ] area/test automation -> area/test-automation
- [ ] env_issue -> env-issue
- [ ] external_integration -> external-integration
- [ ] kind/customer-found -> found/customer
- [ ] kind/automation-found -> found/automation
- [ ] kind/longevity-found -> found/longevity (do we run longevity tests?)
- [ ] kind/nightly-blocker -> found/nightly
- [ ] need-document -> needs/documentation
- [ ] need-test-case -> needs/test-case
- [ ] need-triage -> needs/triage
- [ ] need-reproduction -> needs/repro
- [ ] pending-more-info -> pending/info
- [ ] pending-ux-review -> pending/ux-review
- [ ] photon:2.0 -> area/base-linux
- [ ] security -> area/security

## Merge
I propose we **merge** the following labels:
- [ ] area/helm-chart-repo and area/helm-chart

## +1s :+1:
Would really appreciate some feedback here from the @goharbor/all-maintainers team to make sure this doesn't impact our tooling / workflow.

**Comment by nlowe** [comment]
Two questions:

### Remove

* `cla-not-required`: Is a CLA required for all PR's now?

### Rename

* `area/devops-support` -> `area/operationalization`: What about just `area/ops`?

**Comment by clouderati** [comment]
Contributing to Harbor does not require a CLA now that it's part of the CNCF. The `cla-not-required` label was for VMware employees contributing to Harbor before it was donated.

I like your proposal re: `area/ops`. Will amend the list. Thanks! :+1:

**Comment by clouderati** [comment]
Lazy consensus: if I don't hear any objections by 2dec2018 I'll go ahead and start cleaning up labels.

ping @goharbor/all-maintainers

**Comment by reasonerjt** [comment]
Github issue is the single source of truth for work item management in Harbor.

For example,  **target/*** have been used to track the issues in each release, which is far from optimal, but before we have agreement on another process, removing them will lost track for the planned  items for each release.  Same as **candidate/***, **defer-***

I agree there is a lot of inconsistency and makes it confusing.  I wish to suggest the following before you take action to clean up the labels:
1. Propose a better process for work item management.
2. Propose a convention for label management, clarify the usage of them in the community call.

**Comment by reasonerjt** [comment]
I personally agree the following changes:

## Remove
- [ ] COBD
- [ ] DB change
- [ ] kind/ux-fit-and-finish (use area/ui or area/ux instead)
- [ ] make
- [ ] message
- [ ] needs/validation
- [ ] new-ui
- [ ] UX (use area/ux instead)
- [ ] waiting-for-verify (use needs/repro instead)
- [ ] with-admiral

## Rename
- [ ] area/devops-support -> area/ops
- [ ] area/test automation -> area/test-automation
- [ ] kind/customer-found -> found/customer
- [ ] kind/automation-found -> found/automation
- [ ] kind/longevity-found -> found/longevity (do we run longevity tests?)
- [ ] kind/nightly-blocker -> found/nightly
- [ ] need-document -> needs/documentation
- [ ] need-test-case -> needs/test-case
- [ ] need-triage -> needs/triage
- [ ] need-reproduction -> needs/repro
- [ ] pending-more-info -> pending/info
- [ ] pending-ux-review -> pending/ux-review
- [ ] photon:2.0 -> area/base-linux
- [ ] security -> area/security
### other suggestions
- [ ] env_issue -> env-issue  (how about kind/env-issue)
- [ ] external_integration -> external-integration (how about area/external-integration)

As for the **Merge** section.
**area/helm-chart-repo** and **area/helm-chart** are two different areas one is for the helm chart itself and the other is for the feature "chart repo"

**Comment by cd1989** [comment]
I have some personal suggestions:

1. Change `found` --> `reporter`,  so that `found/customer` --> `reporter/customer`
2. Add some labels to track the status of issues, such as:
- status/new
- status/in-progress
- status/resolved
3. `requirement/status/accepted` --> `requirement/accepted` and other similar labels.
4. Keep `target/*` before we have other replacement.

And do we have document to guide how to use these labels.

**Comment by clouderati** [comment]
Still planning on taking care of this. Hopefully sometime this week (if not early next).

**Comment by steven-zou** [comment]
@reasonerjt 

Clear labels?

**Comment by OrlinVasilev** [comment]
@ghost that's quite old what is the status of this?

**Comment by OrlinVasilev** [comment]
@steven-zou @reasonerjt looks like thats quiiiiite old :) shall we close that ?
