### ISSUE TITLE
Update the CII status of Harbor main project to reasonable stage

### ISSUE THREAD

**Issue by steven-zou** [goharbor/community#48]
On the last TOC call there was a call to look at updating the graduation requirements and also to look at the various CII levels: 
https://github.com/cncf/toc/issues/196

One idea was to potentially have the incubating level require the "silver" level for CII and graduated require the "gold" level:

https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/other.md#silver-passing1-criteria
https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/other.md#gold-passing2-criteria

On the next TOC call, we will have one of the main CII authors to go over the levels and answer any questions from the community. This should be a useful exercise to see if we can leverage the hard work that has been done in CII along with giving them feedback on the criteria they have developed.

**Comment by xaleeks** [comment]
I've started going over checklist, listed here:
https://docs.google.com/spreadsheets/d/1pS2kJMQVuHVN-xfla8Ogex9CqrAKDNo5xLco5ebgaLg/edit#gid=745469121

please ping me for access if interested in helping double check

**Comment by xaleeks** [comment]
this is completed and we have achieved silver badging!! closing
