### ISSUE TITLE
Create roadmap for Harbor project 

### ISSUE THREAD

**Issue by steven-zou** [goharbor/community#68]
The roadmap of Harbor should be defined and keep it in a ROADMAP.md file here.

For the [roadmap file](https://github.com/goharbor/harbor/blob/master/ROADMAP.md) in the harbor project code repo, it can link to the ROADMAP file here.

**Comment by tianon** [comment]
This can probably be closed now, right?  https://github.com/goharbor/harbor/blob/master/ROADMAP.md exists, and points to https://github.com/orgs/goharbor/projects/1 where the roadmap is curated.

**Comment by a-mccarthy** [comment]
closing this as we have a [roadmap file](https://github.com/goharbor/harbor/blob/main/ROADMAP.md) in the goharbor/harbor repo. and have a newer issue for updating the roadmap, https://github.com/goharbor/harbor/issues/14890
